package com.aemerse.muserse.activity

import android.content.Context
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.Fragment
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.aemerse.muserse.R
import com.aemerse.muserse.uiElementHelper.BottomOffsetDecoration
import com.aemerse.muserse.adapter.PlaylistLibraryAdapter

class FragmentPlaylistLibrary: Fragment() {
    private var playlistAdapter: PlaylistLibraryAdapter? = null

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View {
        val layout: View = inflater.inflate(R.layout.fragment_playlist_library, container, false)
        val mRecyclerViewPlaylist = layout.findViewById<RecyclerView>(R.id.recyclerViewSystemPlaylist)
        playlistAdapter = PlaylistLibraryAdapter(requireContext())
        mRecyclerViewPlaylist.adapter = playlistAdapter!!
        mRecyclerViewPlaylist.layoutManager = WrapContentLinearLayoutManager(context)
        val offsetPx = resources.getDimension(R.dimen.bottom_offset_dp)
        val bottomOffsetDecoration = BottomOffsetDecoration(offsetPx.toInt())
        mRecyclerViewPlaylist.addItemDecoration(bottomOffsetDecoration)
        return layout
    }

    fun refreshPlaylistList() {
        playlistAdapter?.refreshPlaylistList()
    }

    //for catching exception generated by recycler view which was causing abend, no other way to handle this
    internal inner class WrapContentLinearLayoutManager constructor(context: Context?) : LinearLayoutManager(context) {
        //... constructor
        override fun onLayoutChildren(recycler: RecyclerView.Recycler, state: RecyclerView.State) {
            try {
                super.onLayoutChildren(recycler, state)
            } catch (ignored: IndexOutOfBoundsException) {
            }
        }
    }
}